# Flake checks, extracted from flake.nix to keep the manifest readable.
# Called per-system as
# `import ./checks.nix { inherit self pkgs importProfilesPkg; }`.
{
  self,
  pkgs,
  # The shared importer derivation (mkImportProfiles in flake.nix), reused
  # here so the script isn't wrapped twice.
  importProfilesPkg,
}:

let
  lib = pkgs.lib;

  # home-manager defines xdg.configFile. Stub it so the module evaluates
  # without home-manager.
  xdgConfigFileStub =
    { lib, ... }:
    {
      options.xdg.configFile = lib.mkOption {
        type = lib.types.attrsOf lib.types.anything;
        default = { };
      };
    };
  evaled = pkgs.lib.evalModules {
    modules = [
      self.homeModules.default
      xdgConfigFileStub
      { slicerProfiles.configDir = "TestSlicer"; }
    ];
  };

  # Evaluate the scaffold template end-to-end. scanDir picks up the example
  # files; mkProfileLib feeds them; the result MUST satisfy the module's option
  # types. Guards the first template users hit against drifting from the
  # lib/module interface.
  templateSlicerLib = self.lib.mkProfileLib { inherit (pkgs) lib; };
  templateProfiles = import ./templates/default/profiles.nix {
    inherit (pkgs) lib;
    slicerLib = templateSlicerLib;
  };
  templateEvaled = pkgs.lib.evalModules {
    modules = [
      self.homeModules.default
      xdgConfigFileStub
      { slicerProfiles = templateProfiles; }
    ];
  };

  # Same, for the #bare variant: no example files, so scanDir yields empty dirs.
  bareTemplateProfiles = import ./templates/bare/profiles.nix {
    inherit (pkgs) lib;
    slicerLib = templateSlicerLib;
  };
  bareTemplateEvaled = pkgs.lib.evalModules {
    modules = [
      self.homeModules.default
      xdgConfigFileStub
      { slicerProfiles = bareTemplateProfiles; }
    ];
  };

  # Fixture for scripts/import-profiles.py: a decimal (MUST port as a string),
  # a whole number (fine as an int), an `inherits =` (the commented
  # vendorBundles hint), and gcode with a literal "\n" and embedded quotes (the
  # importer's escaping MUST round-trip).
  importProfilesFixture = pkgs.writeTextDir "printer/My Printer (test).ini" (
    "nozzle_diameter = 0.4\n"
    + "retract_length = 5\n"
    + "retract_lift = nil\n"
    + "inherits = Some Vendor Printer\n"
    + ''start_gcode = G28\nG1 Z5\n"quoted"''
    + "\n"
  );
  # Vendor fixture for --vendor-src: a matching "[printer:Some Vendor Printer]"
  # section the importer's hint SHOULD resolve by name.
  importProfilesVendorFixture = pkgs.writeTextDir "TestVendor.ini" (
    "[printer:Some Vendor Printer]\nnozzle_diameter = 0.4\n"
  );
  # Two bundles defining the same section. The importer MUST NOT guess; it lists
  # both candidates inline. symlinkJoin merges them into one --vendor-src dir.
  importProfilesTwoVendorsFixture = pkgs.symlinkJoin {
    name = "two-vendors";
    paths = [
      (pkgs.writeTextDir "AlphaVendor.ini" "[printer:Some Vendor Printer]\nnozzle_diameter = 0.4\n")
      (pkgs.writeTextDir "BetaVendor.ini" "[printer:Some Vendor Printer]\nnozzle_diameter = 0.4\n")
    ];
  };
  # Compiled-defaults fixture for --defaults-src (flat key=value, as
  # `prusa-slicer --save` writes it). retract_length matches the profile but
  # isn't in the vendor bundle; start_gcode's default differs, so it stays.
  importProfilesDefaultsFixture = pkgs.writeText "defaults.ini" (
    "# generated by PrusaSlicer\nretract_length = 5\nretract_lift = \nstart_gcode = G28\n"
  );

  # Fixture covers `inherits =` resolution, CRLF, and "key=value" (no space):
  # real vendor-bundle quirks the ini regex MUST handle.
  slicerLib = self.lib.mkProfileLib { inherit (pkgs) lib; };
  vendorFixture = pkgs.writeText "vendor-fixture.ini" (
    "[printer:Base]\nnozzle_diameter = 0.4\r\nretract_length=0.8\r\n"
    + "[printer:Child]\ninherits = Base\nnozzle_diameter = 0.6\n"
  );
  sections = slicerLib.parseVendorIni vendorFixture;
  resolved = slicerLib.resolveVendorSection sections "printer:Child";
  merged = resolved // {
    nozzle_diameter = "0.6";
    extra = "1";
  };
  rendered = slicerLib.toSlic3rIni merged;
  renderedWithInt = slicerLib.toSlic3rIni {
    filament_cost = 20;
    filament_type = "PLA";
  };

  testProfile = {
    name = "Test Printer (nix)";
    value = {
      nozzle_diameter = "0.4";
    };
  };

  basePrinter = {
    name = "Base Printer (nix)";
    value = {
      nozzle_diameter = "0.4";
      retract_length = "0.8";
    };
  };
  derivedPrinter = {
    name = "Derived Printer (nix)";
    value = basePrinter.value // {
      nozzle_diameter = "0.6";
    };
  };

  vendorSrcFixture = pkgs.writeTextDir "TestVendor.ini" (
    "[filament:Test Filament]\nfilament_type = PLA\n"
  );
  testBundle = slicerLib.mkVendorBundle vendorSrcFixture "TestVendor.ini";
  testBundles = slicerLib.mkVendorBundles vendorSrcFixture;

  # Without vendorSrc, mkProfileLib MUST NOT grow a vendorBundles attr; with it,
  # bundles show up pre-attached.
  slicerLibWithVendor = self.lib.mkProfileLib {
    inherit (pkgs) lib;
    vendorSrc = vendorSrcFixture;
  };

  libBehaviorOk =
    assert
      resolved == {
        nozzle_diameter = "0.6";
        retract_length = "0.8";
      };
    assert
      merged == {
        nozzle_diameter = "0.6";
        retract_length = "0.8";
        extra = "1";
      };
    assert rendered == "extra = 1\nnozzle_diameter = 0.6\nretract_length = 0.8\n";
    assert renderedWithInt == "filament_cost = 20\nfilament_type = PLA\n";
    assert !(slicerLib ? vendorBundles);
    assert
      slicerLibWithVendor.vendorBundles.TestVendor "filament:Test Filament" == {
        filament_type = "PLA";
      };
    assert
      builtins.listToAttrs [ testProfile ] == {
        "Test Printer (nix)" = {
          nozzle_diameter = "0.4";
        };
      };
    assert
      derivedPrinter.value == {
        nozzle_diameter = "0.6";
        retract_length = "0.8";
      };
    assert testBundle "filament:Test Filament" == { filament_type = "PLA"; };
    assert
      testBundles.TestVendor "filament:Test Filament" == {
        filament_type = "PLA";
      };
    # A real newline in a value MUST throw, not silently split the ini line.
    assert !(builtins.tryEval (slicerLib.toSlic3rIni { start_gcode = "G28\nG1 Z5"; })).success;
    # The literal "\n" form (backslash-n) renders unchanged.
    assert
      (slicerLib.toSlic3rIni { start_gcode = ''G28\nG1 Z5''; }) == ''
        start_gcode = G28\nG1 Z5
      '';
    true;
in
{
  module-evaluates = pkgs.runCommand "slicer-profiles-nix-module-evaluates" { } ''
    echo "configDir=${evaled.config.slicerProfiles.configDir}" > $out
  '';

  # Force the template's rendered xdg.configFile so lazy evalModules is
  # demanded. The example filament profile MUST show up.
  template-evaluates = pkgs.runCommand "slicer-profiles-nix-template-evaluates" { } ''
    ${lib.concatStringsSep "\n" (
      lib.mapAttrsToList (
        path: entry: "echo ${lib.escapeShellArg "${path}: ${entry.text}"}"
      ) templateEvaled.config.xdg.configFile
    )}
    test "${templateEvaled.config.slicerProfiles.configDir}" = "YourSlicer"
    echo "ok" > $out
  '';

  # The #bare scaffold MUST evaluate with every directory empty.
  bare-template-evaluates = pkgs.runCommand "slicer-profiles-nix-bare-template-evaluates" { } ''
    test "${bareTemplateEvaled.config.slicerProfiles.configDir}" = "YourSlicer"
    test "${toString (builtins.length (builtins.attrNames bareTemplateEvaled.config.xdg.configFile))}" = "0"
    echo "ok" > $out
  '';

  lib-behaves-correctly = pkgs.runCommand "slicer-profiles-nix-lib-behaves-correctly" { } ''
    echo "${pkgs.lib.boolToString libBehaviorOk}" > $out
  '';

  import-profiles-works =
    pkgs.runCommand "slicer-profiles-nix-import-profiles-works"
      {
        nativeBuildInputs = [ importProfilesPkg ];
      }
      ''
        import-profiles --config-dir ${importProfilesFixture} --out $out

        common="$out/printers/_common.nix"
        test -f "$common"

        profile="$out/printers/my_printer_test.nix"
        test -f "$profile"
        grep -qF 'name = "My Printer (test)";' "$profile"
        # No --defaults-src here, so no defaults base layer is written or composed.
        ! test -e "$out/printers/_slicer_defaults.nix"
        ! grep -qF '_slicer_defaults.nix' "$profile"
        grep -qF '# (slicerLib.vendorBundles.<Vendor> "printer:Some Vendor Printer")' "$profile"
        grep -qF '(import ./_common.nix)' "$profile"
        grep -qF '// {' "$profile"
        grep -qF 'nozzle_diameter = "0.4";' "$profile"
        grep -qF 'retract_length = 5;' "$profile"
        grep -qF 'start_gcode = "G28\\nG1 Z5\\n\"quoted\"";' "$profile"
      '';

  import-profiles-vendor-resolves =
    pkgs.runCommand "slicer-profiles-nix-import-profiles-vendor-resolves"
      {
        nativeBuildInputs = [ importProfilesPkg ];
      }
      ''
        import-profiles --config-dir ${importProfilesFixture} --vendor-src ${importProfilesVendorFixture} --out $out

        profile="$out/printers/my_printer_test.nix"
        grep -qF '    (slicerLib.vendorBundles.TestVendor "printer:Some Vendor Printer")' "$profile"
        # resolved - MUST NOT be commented out
        ! grep -qF '# (slicerLib.vendorBundles' "$profile"
        # nozzle_diameter matches the resolved bundle, so it's deduped away.
        ! grep -qF 'nozzle_diameter' "$profile"
        grep -qF 'retract_length = 5;' "$profile"
        grep -qF 'inherits = "Some Vendor Printer";' "$profile"
      '';

  import-profiles-vendor-ambiguous =
    pkgs.runCommand "slicer-profiles-nix-import-profiles-vendor-ambiguous"
      {
        nativeBuildInputs = [ importProfilesPkg ];
      }
      ''
        import-profiles --config-dir ${importProfilesFixture} \
          --vendor-src ${importProfilesTwoVendorsFixture} --out $out

        profile="$out/printers/my_printer_test.nix"
        # Ambiguous - placeholder kept, and the candidates listed inline (sorted).
        grep -qF '(slicerLib.vendorBundles.<Vendor> "printer:Some Vendor Printer")' "$profile"
        grep -qF 'Replace <Vendor> with one of [AlphaVendor, BetaVendor]' "$profile"
      '';

  import-profiles-defaults-dedup =
    pkgs.runCommand "slicer-profiles-nix-import-profiles-defaults-dedup"
      {
        nativeBuildInputs = [ importProfilesPkg ];
      }
      ''
        import-profiles --config-dir ${importProfilesFixture} \
          --vendor-src ${importProfilesVendorFixture} \
          --defaults-src ${importProfilesDefaultsFixture} --out $out

        profile="$out/printers/my_printer_test.nix"
        defaults="$out/printers/_slicer_defaults.nix"

        # The compiled defaults are written as an explicit per-directory base
        # layer the profile composes under everything else.
        test -f "$defaults"
        grep -qF '(import ./_slicer_defaults.nix)' "$profile"

        # retract_length equals the compiled default (not in the bundle) - dropped
        # from the profile's own layer, tracked in the defaults base instead.
        ! grep -qF 'retract_length' "$profile"
        grep -qF 'retract_length = 5;' "$defaults"
        # retract_lift = nil vs "" - unset forms canonicalized equal, same story.
        ! grep -qF 'retract_lift' "$profile"
        grep -qF 'retract_lift = "";' "$defaults"
        # nozzle_diameter still deduped via the vendor bundle (and not a default).
        ! grep -qF 'nozzle_diameter' "$profile"
        ! grep -qF 'nozzle_diameter' "$defaults"
        # start_gcode's default differs, so the override stays; the default value
        # lands in the base layer.
        grep -qF 'start_gcode =' "$profile"
        grep -qF 'start_gcode = "G28";' "$defaults"
        # inherits isn't a compiled default, so it's not in the base layer.
        ! grep -qF 'inherits' "$defaults"
        grep -qF 'inherits = "Some Vendor Printer";' "$profile"
      '';
}
